### ISSUE TITLE
When will you be 1.0 stable?

### ISSUE THREAD

**Issue by rsmayda** [grolston/cfn-security#4]
Hoping to use this action but would prefer to working off a stable non pre-release code

**Comment by grolston** [comment]
Once the implementation of the docker image version is in place we can switch off pre-release. We hope to move this off latest `:latest` this week.

**Comment by grolston** [comment]
Released v1 complete with the master branch and the v1 branch. v1 will not be updated except for bugfixes. New versions will follow updated branches with the master branch following latest version.
